language: python
python:
  - "2.7"
# command to install dependencies,
# e.g. pip install -r requirements.txt --use-mirrors
# install: PLEASE CHANGE ME
install:
  - pip install coveralls
# command to run tests, e.g. python setup.py test
script:
  - coverage run --source seisflows -m unittest discover tests/setup/test_tools

after_success:
  coveralls

