#!/usr/bin/env python

# script to plot velocity models.

import argparse
from os.path import join
from seisflows.tools.graphics import plot_image

# Parse input arguments
parser = argparse.ArgumentParser(description='Plot image.')

# file and format flags
parser.add_argument('file', help='filename')
parser.add_argument('-nx', type=int, help='pixels in x direction.')
parser.add_argument('-nz', type=int, help='pixels in z direction.')
parser.add_argument('-p', '--path', default='.', help='path to velocity model.')
parser.add_argument('-d', '--dtype', default='float32', help='numpy data type.')

# plot options
parser.add_argument('-cm', '--cmap', default='seismic_r', help='Matplotlib colormap scheme. \
                    See matplotlib documentation')

args = parser.parse_args()

file = join(args.path, args.file)

# # execute program
plot_image(file=file, nx=args.nx, nz=args.nz,  dtype=args.dtype, cmap=args.cmap)
