#!/usr/bin/env python

# script to plot velocity models.

import argparse
from seisflows.tools.graphics import plot_model

# Parse input arguments
parser = argparse.ArgumentParser(description='Plot velocity model.')

# file and format flags
parser.add_argument('-nx', type=int, help='pixels in x direction.')
parser.add_argument('-nz', type=int, help='pixels in z direction.')
parser.add_argument('-p', '--path', default='.', help='path to velocity model.')
parser.add_argument('-d', '--dtype', default='float32', help='numpy data type.')

# plot options
parser.add_argument('-m', '--mode',  type=int, choices=[0, 1, 2], default=1, help='Plot Vp, Vp/Vs or Vp/Vs/rho.')
parser.add_argument('-cm', '--cmap', default='seismic_r', help='Matplotlib colormap scheme. \
                    See matplotlib documentation')

args = parser.parse_args()

# execute program
plot_model(nx=args.nx, nz=args.nz, path=args.path, mode=args.mode, dtype=args.dtype, cmap=args.cmap)
