#!/usr/bin/env python

# Specialized script used to plot vectors/time series.

# For convenience this routine assumes a particular directory structure that allows
# simple access to inversion workflows.

import argparse
import numpy as np

from seisflows.tools.graphics import plot_vector


def parse_args():
    # Parse input arguments
    parser = argparse.ArgumentParser(description='Plot vector/time series.')

    # file and format flags
    parser.add_argument('file')
    parser.add_argument('-xl', '--xlabel',
                        default='',
                        help='xlabel')
    parser.add_argument('-yl', '--ylabel',
                        default='',
                        help='ylabel')
    parser.add_argument('-t', '--title',
                        default='',
                        help='Title')

    return parser.parse_args()

if __name__ == "__main__":

    args = parse_args()
    plot_vector(np.loadtxt(args.file), xlabel=args.xlabel, ylabel=args.ylabel, title=args.title)