#!/usr/bin/env python

if __name__ == '__main__':
    import sys

    # parse command line arguments
    mypath = sys.argv[1]
    myclass = sys.argv[2]
    myfunc = sys.argv[3]
    pythonpath = sys.argv[4]

    sys.path.append(pythonpath)

    from os.path import join
    from seisflows.tools.code import loadjson, loadobj
    from seisflows.tools.config import load

    load(mypath)

    # load function arguments
    kwargspath = join(mypath, 'kwargs')
    kwargs = loadobj(join(kwargspath, myclass+'_'+myfunc + '.p'))

    # call function
    func = getattr(sys.modules['seisflows_'+myclass], myfunc)
    func(**kwargs)