#!/usr/bin/env python

if __name__ == '__main__':
    import sys
    from os.path import join
    from mpi4py import MPI

    comm = MPI.COMM_WORLD
    rank = comm.Get_rank()

    # parse command line arguments
    mypath = sys.argv[1]
    myobj = sys.argv[2]
    myfunc = sys.argv[3]
    ntasks = int(sys.argv[4])

    from os.path import join
    from seisflows.tools.code import loadjson, loadobj
    from seisflows.tools.config import SeisflowsObjects, SeisflowsParameters, SeisflowsPaths

    # reload from last checkpoint
    for obj in [SeisflowsParameters(), SeisflowsPaths(), SeisflowsObjects()]:
       obj.reload(mypath)

    PAR = SeisflowsParameters()
    PATH = SeisflowsPaths()

    # load function arguments
    kwargspath = join(mypath, 'SeisflowsObjects', myobj + '_kwargs')
    kwargs = loadobj(join(kwargspath, myfunc + '.p'))

    # call function
    func = getattr(sys.modules[myobj], myfunc)

    id = 'rank_{:03d}'.format(rank)
    path = join(PATH.SUBMIT, id)
    for itask in range(ntasks):
        with open(path, 'w') as f:
            f.write(str(itask))

        func(**kwargs)

    comm.Barrier()

